name: Cache

on:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reactor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23

      - name: Build Reactor
        id: build
        run: echo "path=$(nix build .#packages.x86_64-linux.reactor --no-link --print-out-paths)" >> "$GITHUB_OUTPUT"

      - name: Log in to Attic
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        run: |
          nix profile install nixpkgs#attic-client
          attic login reactor https://cache.cum.army/ "$ATTIC_TOKEN"

      - name: Push Reactor closure
        run: attic push reactor "${{ steps.build.outputs.path }}"
